news/urls.py
from cgitb import handler
from unicodedata import name
from django import views
from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('userguide', userguide, name='userguide'),
    path('export_excel', export_excel, name='export-excel'),
    path('news/', news, name='news'),
    path('news/<slug:new_slug>/', show_new, name='new'),
    path('tarifs/', tariffs, name='tariffs'),
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('director/', director, name='director'),
    path('requisites/', requisites, name='requisites'),
    path('search/', search, name='search'),
    path('consumerinfo/', consumerinfo, name='consumerinfo'),
    path('sitemap/', sitemap, name='sitemap'),
]

pts/urls.py
from cgitb import handler
from django.conf import settings
from django.contrib import admin
from django.urls import path
from news.views import *
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),


]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = "news.views.pageNotFound"

news/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


class News(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(max_length=255, unique=True,
                            db_index=True, verbose_name="URL(slug)")
    brief = models.TextField(blank=False, verbose_name="Краткое описание")
    content = RichTextField(blank=False, verbose_name="Контент")
    photo = models.ImageField(
        upload_to='photos/%Y-%m-%d', verbose_name="Фото", blank=True)
    time_create = models.DateTimeField(
        auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(
        auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(default=True, verbose_name="Публикация")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('new', kwargs={'new_slug': self.slug})

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['time_create', 'title']


class GVS(models.Model):
    street = models.CharField(verbose_name='Улица', max_length=50)
    build = models.CharField(verbose_name='Дом', max_length=50)
    REGIONS = (
        ('Северный сетевой район', 'Северный сетевой район'),
        ('Южный сетевой район', 'Южный сетевой район'),
    )
    rem_obj = models.CharField(
        verbose_name='ТК,НО, ЦТП', max_length=50, default='')
    region = models.CharField(
        verbose_name='Сетевой район', max_length=50, choices=REGIONS)
    date_disconnect = models.DateField(verbose_name="Дата отключения")
    date_connect = models.DateField(
        verbose_name="Ориентировочная дата устранения")
    reason = models.CharField(
        verbose_name='Причина отсутствия ГВС', max_length=250)
    is_published = models.BooleanField(default=True, verbose_name="Публикация")

    def __str__(self):
        return f'{self.region} {self.street} {self.build}'

    class Meta:
        verbose_name = 'Элемент списка'
        verbose_name_plural = 'Список домов Северного и Южного сетевых районов, в которых отсутствует ГВС'
        ordering = ['id', 'region', 'street', 'build']


class Contact(models.Model):
    name = models.CharField(max_length=200, verbose_name="Имя")
    email = models.EmailField(max_length=200, verbose_name="E-mail")
    MT = (
        ('Общие вопросы', 'Общие вопросы'),
        ('Претензии|Жалобы|Замечания к работе',
         'Претензии|Жалобы|Замечания к работе'),
        ('Диспетчерская служба', 'Диспетчерская служба'),
        ('Тепловая инспекция', 'Тепловая инспекция'),
    )
    message_type = models.CharField(
        max_length=50, choices=MT, default="Выберите тип сообщения", verbose_name="Тип сообщения")
    message = models.TextField(max_length=1000, verbose_name="Текст сообщения")
    income_date = models.DateField(auto_now=True, verbose_name="Дата")
    is_read = models.BooleanField(default=False, verbose_name="Прочитано")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Элемент обратной связи'
        verbose_name_plural = 'Обратная связь'
        ordering = ['id', 'name', 'email']

news/forms.py
from email import message
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message_type', 'message']

        # widgets = {"name": forms.TextInput(
        #     attrs={"form_control valid"}),  "message": forms.Textarea(attrs={"class": "form_control valid"}), }
        MT = (
            ('Общие вопросы', 'Общие вопросы'),
            ('Претензии|Жалобы|Замечания к работе',
             'Претензии|Жалобы|Замечания к работе'),
            ('Диспетчерская служба', 'Диспетчерская служба'),
            ('Тепловая инспекция', 'Тепловая инспекция'),
        )
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Ваше имя', 'class': "form_control valid"}),
            'email': forms.TextInput(attrs={'placeholder': 'E-mail',
                                            'cols': 30,
                                            'rows': 9,
                                            'class': "form_control valid"}),
            'message_type': forms.Select(attrs={'class': "form_control valid"}),
            'message': forms.Textarea(attrs={'placeholder': 'Введите текст собщения', 'cols': 30, 'rows': 9, 'class': "form_control valid"}),
        }

news/views.py
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .forms import ContactForm
from .models import *
from django.core.paginator import Paginator
from .filters import FindGVSItem
import xlwt
from datetime import date
from django.template.loader import get_template


def index(request):
    last_news = News.objects.filter(
        is_published=True).order_by("-time_create")[0:3]

    result = GVS.objects.filter(
        is_published=True).order_by('region', 'street').distinct()

    myFilter = FindGVSItem(request.GET, queryset=result)
    result = myFilter.qs

    context = {
        'last_news': last_news,

        'title': 'ТОО "Павлодарские тепловые сети"',
        'results_list': result,
        'myFilter': myFilter
    }

    return render(request, 'news/index.html', context)


def export_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=GVSFullList_' + \
        str(date.today())+'.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Информация на ' + str(date.today()))

    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.font.height = 280
    font_style.alignment.wrap = 1
    font_style.alignment.horz = xlwt.Alignment.HORZ_CENTER
    font_style.font.name = 'Times New Roman'

    ws.write_merge(
        1, 1, 2, 8, "Перечень многоэтажных жилых домов, где отсутствует горячее водоснабжение по состоянию на " + str(date.today()), font_style)

    row_num = 5
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    font_style.alignment.wrap = 1
    font_style.font.height = 240
    font_style.borders.top = 1
    font_style.borders.right = 1
    font_style.borders.left = 1
    font_style.borders.bottom = 1
    font_style.alignment.horz = xlwt.Alignment.HORZ_CENTER

    columns = ['№ п/п', 'Сетевой район', 'Улица', 'Дом', 'Дата отключения',
               'Ориентир. дата устранения', 'Причина']

    ws.col(2).width = 1200  # №
    ws.col(3).width = 8000  # Сетевой район
    ws.col(4).width = 6000  # Улица
    ws.col(5).width = 2000  # Дом
    ws.col(6).width = 4000  # Дата отключения
    ws.col(7).width = 4000  # Ориентир. дата подключения
    ws.col(8).width = 15000  # Причина

    for col_num in range(len(columns)):
        ws.write(row_num, col_num + 2, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    font_style.font.height = 240
    font_style.alignment.wrap = 1
    font_style.borders.top = 1
    font_style.borders.right = 1
    font_style.borders.left = 1
    font_style.borders.bottom = 1
    font_style.font.name = 'Times New Roman'
    font_style.alignment.horz = xlwt.Alignment.HORZ_CENTER

    rows = GVS.objects.all().values_list('id', 'region', 'street', 'build',
                                         'date_disconnect', 'date_connect', 'reason')

    for row in rows:
        row_num += 1

        for col_num in range(len(row)):
            ws.write(row_num, col_num + 2, str(row[col_num]), font_style)
    wb.save(response)

    return response


def news(request):
    news_items = News.objects.filter(
        is_published=True).order_by("-time_create")

    paginator = Paginator(news_items, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'title': 'Новости',
        'page_obj': page_obj,
    }

    return render(request, 'news/news.html', context)


def show_new(request, new_slug):
    new = get_object_or_404(News, slug=new_slug)

    context = {
        'new': new,
        'title': new.title,
    }

    return render(request, 'news/new.html', context=context)


def tariffs(request):

    context = {
        'title': 'Тарифы',
    }
    return render(request, 'news/tariff.html', context)


def contacts(request):
    context = {
        'title': 'Контакты',
    }

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            send_message(
                form.cleaned_data['name'], form.cleaned_data['email'], form.cleaned_data['message'])
            context = {'success': 1}

    else:
        form = ContactForm()

    context['form'] = form

    return render(request, 'news/contacts.html', context=context)


def send_message(name, email, message):
    text = get_template('news/message.html')
    html = get_template('news/message.html')
    context = {'name': name, 'email': email, 'message': message}
    subject = 'Сообщение от пользователя'
    from_email = 'from@example.com'
    text_content = text.render(context)
    html_content = html.render(context)

    msg = EmailMultiAlternatives(subject, text_content, from_email, [
                                 'admin@example.com'])
    msg.attach_alternative(html_content, 'text/html')
    msg.send()


def success(request):
    return HttpResponse('Письмо отправлено!')


def about(request):

    context = {
        'title': 'Общая информация',
    }

    return render(request, 'news/about.html', context)


def director(request):

    context = {
        'title': 'Руководитель',
    }

    return render(request, 'news/director.html', context)


def requisites(request):

    context = {
        'title': 'Реквизиты',
    }

    return render(request, 'news/requisites.html', context)


def consumerinfo(request):
    context = {
        'title': 'Потребителям',
    }

    return render(request, 'news/consumerinfo.html', context)


def sitemap(request):
    context = {
        'title': 'Карта сайта',
    }

    return render(request, 'news/sitemap.html', context)


def pageNotFound(request, exception):
    return render(request, 'news/404.html', status=404)


def userguide(request):
    context = {}
    return(request, 'news/404.html', context)


def search(request):

    if request.method == "POST":
        searched = request.POST['q']
        news_list = News.objects.raw('SELECT * FROM news_news WHERE title iLIKE %s OR brief iLIKE %s OR content iLIKE %s', [
            '%'+searched+'%', '%'+searched+'%', '%'+searched+'%'])

    paginator = Paginator(news_list, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'news/search.html',  {'searched':  searched, 'title': 'Результаты поиска',  'page_obj': page_obj, })

news/templates/news/about.html
{% extends 'news/base.html' %} {% block content %}

<section class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{% url 'home' %}">Главная</a></li>
          <li><a href="{% url 'about' %}">О компании</a></li>
          <li>{{title}}</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="about">
  <div class="container">
    <div class="col-md-12">
      <div class="about_info">
        <h1 class="news_title"><span>{{ title }}</span></h1>
      </div>
      <div class="about_wrap col-md-12">
        <div class="about_descr">
          ТОО «Павлодарские тепловые сети» осуществляет передачу и распределение
          тепловой энергии для потребителей городов Павлодар и Экибастуз.
          Деятельность предприятия направлена на совершенствование
          эксплуатационной надежности тепловых сетей и обеспечение координации
          процессов выработки, передачи и потребления тепловой энергии.
        </div>
        <div class="about_descr">
          ТОО «Павлодарские тепловые сети» образовано и осуществляет свою
          деятельность в г. Павлодар с 28 сентября 2006 года.
        </div>
        <div class="about_descr">
          Всего тепловых сетей в городе Павлодаре 742,2 км, в том числе сетей
          потребителей 322,3 км. ТОО «Павлодарские тепловые сети» производит
          эксплуатацию тепловых сетей и сетей горячего водоснабжения
          протяженностью 419,9 км, из них:
          <ul class="about_descr_seti">
            <li>магистральных тепловых сетей — 115 км;</li>
            <li>квартальных тепловых сетей — 281,9 км;</li>
            <li>сетей горячего водоснабжения — 23,0 км;</li>
            <li>насосных станций — 11 шт.;</li>
            <li>центральных тепловых пунктов — 22 шт.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

news/templates/news/consumerinfo.html
{% extends 'news/base.html' %} {% load static %} {% block content %}

<section class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{% url 'home' %}">Главная</a></li>
          <li>{{title}}</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="info">
  <div class="container">
    <div class="col-md-12">
      <div class="info_head">
        <h3 class="news_title"><span>{{ title }}</span></h3>
      </div>
      <div class="col-md-12">
        <img
          class="info_consumer_img"
          src="{% static 'news/images/consumerinfo.jpg' %}"
          alt="Информационное фото о подготовке к отопительному сезону"
        />
        <div class="info_text">
          Информация для потребителей по подготовке к отопительному сезону – для
          получения ежегодного Акта технической готовности теплопотребляющих
          установок и теплосетей потребителя к работе в осенне-зимний период
        </div>

        <a
          class="info_consumer_btn"
          target="_blank"
          href="{% static 'news/downloads/forconsumers/tex.trebovanie-18-19g.g.doc' %}"
        >
          <i class="fas fa-download"></i> Скачать
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

news/templates/news/director.html
{% extends 'news/base.html' %} {% load static %} {% block content %}

<section class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="{% url 'home' %}">Главная</a></li>
          <li><a href="{% url 'about' %}">О компании</a></li>
          <li>{{title}}</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<div class="info">
  <div class="container">
    <div class="col-md-12">
      <div class="info_head">
        <h3 class="news_title"><span>{{ title }}</span></h3>
      </div>
      <div class="col-md-12">
        <img
          class="info_img"
          src="{% static 'news/images/imanaev.jpg' %}"
          alt="Фото руководителя"
        />
        <div class="info_title">
          <h2 class="info_title_name">Иманаев Марат Шамильевич</h2>
          <h2 class="info_title_job">
            Генеральный директор ТОО «Павлодарские тепловые сети»
          </h2>
        </div>
        <div class="info_text">
          Иманаев Марат Шамильевич родился 22 мая 1969 года в городе Темиртау.
          Имеет высшее техническое образование, окончил Павлодарский
          государственный университет им. С. Торайгырова по специальности
          «Электроэнергетика». Трудовую деятельность начал в 1984 году с
          должности трубоукладчика 3-го разряда СУ «Земдорстрой» треста
          «Металлургжилстрой».

          <ul>
            <li>
              В 1998 году принят заместителем генерального директора по
              коммерции в ТОО «Компания ССL-Энерго».
            </li>
            <li>
              В 2000 году назначен генеральным директором ТОО
              «Теплоцентр-Северный». С 2002 года президент АО «Энергоцентр», с
              2005 года – президент АО «Павлодарэнергосервис».
            </li>
            <li>В 2007 году – директор ТОО «Экибастузские тепловые сети».</li>
            <li>
              С февраля 2008 года приступил к исполнению обязанностей президента
              АО «КОКШЕ».
            </li>
            <li>
              С 2010 года по апрель 2015 года – директор департамента управления
              ТЭК корпорации «Казахмыс».
            </li>
            <li>
              В июне 2015 года назначен генеральным директором ТОО "Павлодарские
              тепловые сети".
            </li>
            <li>
              В 2019 году присвоено звание «Заслуженный энергетик» Казахстанской
              Электроэнергетической Ассоциации.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

news/templates/news/index.html
{% extends 'news/base.html' %} 


{% block content %} 

 <section class="promo">
      <div class="container">
        <div class="row">
          <div class="inner-wrapper col-md-12">
                <p class="promo_subheader animate__animated animate__zoomIn">
                    Надежно и качественно
                    <br>
                    Обеспечиваем тепловой энергией родной город
                </p>
            <a class="promo_btn animate__animated animate__backInUp animate__delay-1s btn btn-primary btn-ghost btn-offset" href="{% url 'about' %}">читать подробнее</a>
          </div>
        </div>
      </div>
    </section>

      <section class="GVS">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                <div class="news_main_header">
                    <h1 class="news_title"><span>Отключения</span></h1>
                  </div>

                    <div class="GVS_info">
                      <ul>
                        <li>                 
                          <a class="toggle_btn" id="toggle_btn1"><i class="fas fa-plus"></i> Разъяснение по причинам отсутствия ГВС в многоэтажных жилых домах Павлодара</a>
                          <div class="toggle_box" id="toggle_box1">
                      <table class="tariff_table table_info">
                                                <tbody>
                                                  <tr>
                                                    <th>
                                                      <p>Причина</p>
                                                    </th>
                                                    <th>
                                                      <p>Пояснение</p>
                                                    </th>
                                                </tr>
                                                  <tr>
                                                    <td>
                                                      <p>Повреждение</p>
                                                    </td>
                                                    <td>
                                                      <p>Повреждения тепловых сетей выявляются в ходе проведения гидравлических испытаний. После обнаружения повреждения тепловики проводят ремонтные работы на участке (внутриквартальных или магистральных сетей).</p>
                                                    </td>
                                                  </tr>
                                                  <tr>
                                                    <td>
                                                      <p>Капитальный ремонт</p>
                                                    </td>
                                                    <td>
                                                      <p>Капитальный ремонт включает в себя полную замену изношенного участка тепломагистрали или внутриквартальной сети на новые трубы.</p>
                                                    </td>
                                                  </tr>
                                                  <tr>
                                                    <td>
                                                      <p>Реконструкция тепловой сети</p>
                                                    </td>
                                                    <td>
                                                      <p>Реконструкция тепловой сети – это модернизация тепловых сетей путем увеличения их диаметра. Эти работы позволяют увеличить нагрузку на сети и сократить количество порывов.</p>
                                                    </td>
                                                  </tr>
                                                  <tr>
                                                    <td>
                                                      <p>Отсутствие тех.возможности</p>
                                                    </td>
                                                    <td>
                                                      <p>Отсутствие технологической возможности связано с выводом в плановый ремонт оборудования Павлодарских ТЭЦ-1 и ТЭЦ-3. В данный момент проводится поэтапное подключение потребителей на сетях, где отсутствуют повреждения.</p>
                                                    </td>
                                                  </tr>
                                                  <tr>
                                                    <td>
                                                      <p>Работы, проводимые КСК</p>
                                                    </td>
                                                    <td>
                                                      <p>Этот пункт означает, что со стороны тепловиков все работы по ремонту теплосетей и подаче ГВС завершены, но горячая вода отсутствует из-за проведения работ с внутридомовым оборудованием. По вопросам завершения этих работ следует обращаться в КСК по месту жительства.</p>
                                                    </td>
                                                  </tr>
                                                </tbody>
                      </table>
                          </div>
                        </li>
                        <li>
                          <a class="toggle_btn" id="toggle_btn2"><i class="fas fa-question"></i> Почему на разрытом участке не проводятся работы?</a>
                          <div class="toggle_box" id="toggle_box2">
                    <p>Если на разрытом участке не проводятся работы, это не значит, что ремонтная бригада их не выполняет. От ТЭЦ к потребителям идут тепломагистрали, от них – внутриквартальные сети. Соответственно, сначала проводятся работы на магистралях, после – на внутриквартальных сетях, запитанных от нее. </p>
                        </div>
                        </li>
                        <li>
                          <a class="toggle_btn" id="toggle_btn3"><i class="fas fa-question"></i> Почему мой дом не указан в списке, хотя в нем нет горячей воды?</a>
                          <div class="toggle_box" id="toggle_box3">
                    <p>Списки обновляются ежедневно, и, если ваш дом не указан в списке, возможно информация по нему уточняется. В этом случае рекомендуем ознакомиться со сроками, указанными рядом с соседними домами. Как правило, почти все дома в определенном районе подключены к одной отопительной системе, сроки для них идентичны. </p>
                        </div>
                        </li>
                        <li>
                          <a class="toggle_btn" id="toggle_btn4"><i class="fas fa-question"></i> Почему указываются только ориентировочные сроки?</a>
                          <div class="toggle_box" id="toggle_box4">
                      <p>Во время испытаний, а также после них продолжают выявляться повреждения, что обусловлено, в первую очередь, высокой степенью износа тепловых сетей - 81%, в связи с чем и растет число повреждений. В ближайшие сроки тепловики определят окончательный объем работ и предоставят более точные сроки появления ГВС в домах Павлодара.</p>
                          </div>
                        </li>
                      </ul>
                  </div>
                  
                  <div class="form">
                    <div class="form_header">Проверить дом на отсуствие ГВС:</div>
                    <div class="form_block" id="form_block">
                      <form method="GET">
                      <label class="form_label" for="id_street">Улица: </label>
                      <input type="text" name="street" class="form-control mb-2" id="id_street"  list="streets">
                        
                        <datalist id="streets">
                          {% for r in results  %}
                          <option value="{{ r }}">{{  r.street }}</option>
                          {% endfor %}
                        </datalist>

                      <label class="form_label" for="id_build">Дом: </label>
                      <input type="text" name="build" class="form-control mb-2" id="id_build">
                      <!-- <div class="form_btn_block"> -->
                      <button class="form_btn" id="form_btn">Найти</button>
                        <button class="form_btn" id="form_btn">Показать все</button>
                      <!-- </div> -->
                      </form>
                    </div>
                  </div>

                  <a  href="{% url 'export-excel' %}" class="excel_block"><i class="fas fa-file-excel"></i> Скачать полный список</a>
          
                    {% if not results_list %}
                      <div class="searchempty_block">
                        <p class="searchempty_descr">Информации по отсуствию ГВС нет.</p>
                      </div>
                    {% else %}
                    <div class="table_block">
                    <table class="tariff_table table_info">
                      <tbody>
                        <tr>
                          <th>
                            <p>Сетевой район</p>
                          </th>
                          <th>
                            <p>Адрес</p>
                          </th>
                          <th>
                            <p>Дом</p>
                          </th>
                          <th>
                            <p>Дата отключения</p>
                          </th>
                            <th>
                            <p>Ориентировочная дата устранения</p>
                          </th>
                          <th>
                            <p>Причина</p>
                          </th>
                        </tr>
                        {% for l in results_list %}
                        <tr>
                          <td>
                            <p>{{ l.region }}</p>
                          <td>
                            <p>{{ l.street }}</p>
                          </td>
                          <td>
                            <p>{{ l.build }}</p>
                          </td>
                          <td>
                            <p>{{ l.date_disconnect }}</p>
                          </td>
                          <td>
                            <p>{{ l.date_connect }}</p>
                          </td>
                          <td>
                            <p>{{ l.reason }}</p>
                          </td>
                        </tr>
                          {% empty %}
                      <div class="searchempty_block">
                        <p class="searchempty_descr">Ничего не найдено. Проверьте правильность ввода дома и адреса, а затем повторите попытку.</p>
                      </div>
                          {% endfor %}
                      </tbody>
                    </table>
                    {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section>


    <section class="news">
      <div class="container">
        <div class="row">
           <div class="col-md-12 ">
            <div class="news_main_header">
              <h1 class="news_title"><span>Последние новости</span></h1>
            </div>
           </div>
          <div class="col-md-12">
            {% if not last_news %}
                          <div class="searchempty_block">
                <p class="searchempty_descr">На данный момент последние новости отсуствуют.</p>
              </div>
            {% else %}
            {% for l in last_news %}
            <div class="news_item">
              <a class="news_header" href="{{ l.get_absolute_url }}"><h5 class="news_header">{{l.title}}</h5></a>
              <p class="news_date">{{l.time_create}}</p>
              <div class="news_descr">
                 {% if l.photo %}
                  <img class="news_img" src="{{l.photo.url}}" alt="Фото новости" 
                  onclick="javascript:document.location.href='{{ l.get_absolute_url }}'">
            
                {% endif %}
                 <p class="news_text" >{{l.brief}}</p>
              </div>
               <a class="news_btn" href="{{ l.get_absolute_url }}">Подробнее</a>
            </div>
          {% endfor %}
         {% endif %}
            <a class="news_btn_all" href="{% url 'news' %}">Все новости</a>
        </div>
      </div>
    </section>

    
     <section class="sitemap">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
           <a href="{% url 'sitemap' %}" class="sitemap_link" ><i class="fas fa-sitemap"></i> Карта сайта</a>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

news/templates/news/message.html
Здравствуйте! Новое сообщение с сайта. Имя: {{ name }} E-mail: {{ email }}
Сообщение: {{ message }}